[package]
name = "vera-mmu-desktop"
version = "0.1.0-4"
description = "Application desktop contrôlée de VERA-MMU"
authors = ["VERA-MMU contributors"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
rand = "0.8"
rfd = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
